"""Replay a previously-captured demo trace at recording-friendly cadence.

The real trace was generated by ``demo_walk.py`` driving a real Claude
session against the incident_response MCP server (cost: ~$0.50). To
avoid burning $0.50 every time the GIF is re-recorded, we ship the
captured stdout and replay it here with deliberate pauses at section
boundaries.

What's recorded: real natural-language input, real Claude tool calls,
real server responses parsed from shipped Alertmanager data. The
playback timing is the only thing that's synthetic.
"""

from __future__ import annotations

import sys
import time
from pathlib import Path

TRACE = Path(__file__).parent / "demo_recorded_trace.txt"


def main() -> None:
    # When recording the hero GIF (a tty), wipe the launch command off
    # screen and pause briefly so the capture starts on the transcript,
    # not on a Python invocation. No-op when piped (demo_walk capture).
    if sys.stdout.isatty():
        sys.stdout.write("\033[2J\033[3J\033[H")
        sys.stdout.flush()
        time.sleep(0.6)
    lines = TRACE.read_text().splitlines(keepends=True)
    for raw in lines:
        sys.stdout.write(raw)
        sys.stdout.flush()
        # Tune cadence by line shape:
        stripped = raw.strip()
        if "claude →" in stripped:
            # Each tool-call header gets a beat before the outcome.
            time.sleep(0.45)
        elif stripped.startswith(("\033[32m✓", "\033[31m✗")):
            # Outcome lines get a longer pause so the eye lands on them.
            time.sleep(0.75)
        elif stripped.startswith(("─", "\033[1;36m─")):
            # Section dividers get a clear break.
            time.sleep(0.4)
        elif not stripped:
            time.sleep(0.08)
        else:
            time.sleep(0.03)


if __name__ == "__main__":
    main()
